export const routeLinks = {
  userManageLink: '/system/user-manage',
  userReduxLink: '/system/user-redux',
  userDoctorLink: '/system/doctor-user',
  userAdminLink: '/system/admin-user',
  userClinicLink: '/system/clinic-manager',
  userSpecialityLink: '/system/speciality-manager',
  userHandbookLink: '/system/handbook-manager',
};

export const textLangs = {
  userManagerL: 'system.user-manage.userManager',
  addAnUserL: 'system.user-manage.addAnUser',
  sttL: 'system.user-manage.stt',
  createNewUserL: 'system.user-manage.create-newUser',
  emailL: 'system.user-manage.email',
  avatarL: 'system.user-manage.avatar',
  passwordL: 'system.user-manage.password',
  passwordConfirmedL: 'system.user-manage.passwordConfirmed',
  firstnameL: 'system.user-manage.firstname',
  lastnameL: 'system.user-manage.lastname',
  addressL: 'system.user-manage.address',
  mobileL: 'system.user-manage.mobile',
  genderL: 'system.user-manage.gender',
  roleL: 'system.user-manage.role',
  positionL: 'system.user-manage.position',
  createL: 'system.user-manage.create',
  saveL: 'system.user-manage.save',
  cancelL: 'system.user-manage.cancel',
  loadImg: 'system.user-manage.loadImg',
};
