const actionTypes = Object.freeze({
  PROCESS_LOGOUT: 'PROCESS_LOGOUT',

  //app
  APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
  SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',
  CHANGE_LANGUAE: 'CHANGE_LANGUAE',
  SAVING_PREVIEW_URL: 'SAVING_PREVIEW_URL',
  REMOVING_PREVIEW_URL: 'REMOVING_PREVIEW_URL',

  //user,
  ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
  USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
  ACTIVE_MENU: 'ACTIVE_MENU',

  //admin
  FETCHING_API: 'FETCHING_API',
  FETCH_GENDER_ROLE_POS_API_SUCCESSED: 'FETCH_GENDER_ROLE_POS_API_SUCCESSED',
  FETCH_GENDER_ROLE_POS_API_FAILED: 'FETCH_GENDER_ROLE_POS_API_FAILED',

  CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
  CREATE_USER_FAILED: 'CREATE_USER_FAILED',

  // 14ms24ss
  FETCH_USER_LIST_SUCCESS: 'FETCH_USER_LIST_SUCCESS',
  FETCH_USER_LIST_FAILED: 'FETCH_USER_LIST_FAILED',
  USER_LIST_REDUX: 'USER_LIST_REDUX',
  UPDATE_USER_LIST_REDUX: 'UPDATE_USER_LIST_REDUX', //32ms12ss

  // 58ms08ss
  DEL_USER_SUCCESS: 'DEL_USER_SUCCESS',
  DEL_USER_FAILED: 'DEL_USER_FAILED',

  // v70xx2
  UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
  UPDATE_USER_FAILED: 'UPDATE_USER_FAILED',
});

export default actionTypes;
